### ISSUE TITLE
论文中figure 4的（b）framework中，

### ISSUE THREAD

**Issue by XiaoZong0** [ASC8384/UniCoder#1]
下面的图为什么是Multilingual Code 通过code LLM生成 Universal Code + Multilingual Code & Problem Solution
![image](https://github.com/ASC8384/UniCoder/assets/49575083/a32cb311-db90-4810-91d5-13768c431e88)

**Comment by ASC8384** [comment]
您好，这里指的是，原始代码通过提示LLM生成Universal Code，之后结合Universal Code生成目标代码/解决方案
